version: "1"
services:
  app:
    build: ./
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    container_name: db-books
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_api
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
